export const BREADCRUMB_LABELS: Record<string, string> = {
  dashboard: "Trang chủ",
  tables: "Bàn",
  manage: "Điều chỉnh",
  staff: "Nhân viên",
  menu: "Thực đơn",
  category: "Danh mục món ăn",
  "menu-item": "Món ăn",
  settings: "Cài đặt",
  pos: "POS",
  orders: "Đơn hàng",
  bill: "Hóa đơn",
  setting: "Cài đặt ứng dụng",
  member: "Thành viên",
  point: "Điểm",
};
